name: Publish to GitHub Packages

on:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          registry-url: "https://npm.pkg.github.com/"

      - name: Create .npmrc for Authentication
        run: echo "//npm.pkg.github.com/:_authToken=${{ secrets.GH_PACKAGES_PAT }}" > ~/.npmrc

      - name: Install Dependencies
        run: npm install

      - name: Build Package
        run: npm run build

      - name: Publish to GitHub Packages
        run: npm publish
